# Generated by Django 4.2.1 on 2023-09-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('molding', models.CharField(max_length=255)),
                ('portal', models.CharField(max_length=255)),
            ],
        ),
    ]
