# Generated by Django 4.2.1 on 2023-09-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doors',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green')], max_length=10),
        ),
        migrations.AlterField(
            model_name='doors',
            name='molding',
            field=models.CharField(choices=[('none', 'None'), ('simple', 'Simple'), ('ornate', 'Ornate')], max_length=10),
        ),
        migrations.AlterField(
            model_name='doors',
            name='portal',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double')], max_length=10),
        ),
        migrations.AlterField(
            model_name='doors',
            name='shape',
            field=models.CharField(choices=[('square', 'Square'), ('rectangle', 'Rectangle'), ('round', 'Round')], max_length=10),
        ),
    ]
