# Generated by Django 4.2.1 on 2023-09-19 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_doors_color_alter_doors_molding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_colors', to='Main.attribute')),
                ('molding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_molding', to='Main.attribute')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_portal', to='Main.attribute')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_shapes', to='Main.attribute')),
            ],
        ),
        migrations.DeleteModel(
            name='Doors',
        ),
    ]
