# Generated by Django 4.2.1 on 2023-10-10 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_door_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portal',
            name='molding',
        ),
        migrations.AddField(
            model_name='molding',
            name='portal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Main.portal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portal',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Bevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.portal')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.shape')),
            ],
        ),
        migrations.AddField(
            model_name='door',
            name='bevel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Main.bevel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='molding',
            name='bevel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Main.bevel'),
            preserve_default=False,
        ),
    ]
