# Generated by Django 4.2.1 on 2023-09-19 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_attribute_door_delete_doors'),
    ]

    operations = [
        migrations.CreateModel(
            name='molding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Attribute',
            new_name='color',
        ),
        migrations.AlterField(
            model_name='door',
            name='molding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_molding', to='Main.molding'),
        ),
        migrations.AlterField(
            model_name='door',
            name='portal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_portal', to='Main.portal'),
        ),
        migrations.AlterField(
            model_name='door',
            name='shape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_shapes', to='Main.shape'),
        ),
    ]
