# Generated by Django 4.2.1 on 2023-10-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_order_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_list',
            new_name='Basket',
        ),
    ]
