# Generated by Django 4.2.1 on 2023-10-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_rename_order_list_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='count',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
