# Generated by Django 4.2.1 on 2023-10-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_basket_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='count',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=5),
        ),
    ]
