# Generated by Django 4.2.1 on 2023-10-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_alter_basket_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='molding',
            name='bevel',
        ),
        migrations.RemoveField(
            model_name='molding',
            name='portal',
        ),
        migrations.RemoveField(
            model_name='molding',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='portal',
            name='shape',
        ),
        migrations.AddField(
            model_name='door',
            name='collection',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='door',
            name='bevel',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='door',
            name='color',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='door',
            name='molding',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='door',
            name='portal',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='door',
            name='shape',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.DeleteModel(
            name='Bevel',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Molding',
        ),
        migrations.DeleteModel(
            name='Portal',
        ),
        migrations.DeleteModel(
            name='Shape',
        ),
    ]
