# Generated by Django 4.2.1 on 2023-10-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_remove_molding_bevel_remove_molding_portal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='collection',
            field=models.CharField(default='Classic', max_length=100),
        ),
    ]
